In [3]:
import numpy as np

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   --------------- ------------------------ 5.0/12.7 MB 30.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 31.1 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 28.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
import Numpy as np

ModuleNotFoundError: No module named 'Numpy'

In [5]:
import numpy as np

In [6]:
x = array.np([1, 2, 3])


NameError: name 'array' is not defined

In [7]:
x = np.array([1,2])

In [8]:
print(x)


[1 2]


In [ ]:
x = np.array([2, 3, 10, 12, 17])


In [10]:
print(np.where(x == 10))

(array([2]),)


In [11]:
x = np.array([4,9,3,2,8])


In [16]:
print(np.sort(x))

[2 3 4 8 9]


In [24]:
ab = np.array([3,4,5,6,2,9])

In [25]:
print(ab.reshape(3, 2))

[[3 4]
 [5 6]
 [2 9]]


In [30]:
m = np.array([5,6,7,8,9,10,3,2,1])

In [31]:
print(m[4:7])

[ 9 10  3]


In [35]:
xy = np.array([[1,2,3], [4,5,6]])

In [36]:
print(xy)

[[1 2 3]
 [4 5 6]]


In [38]:
mn = np.array([[[1,4,3], [5,6,7], [8,9,10]]])

In [41]:
print(mn)

[[[ 1  4  3]
  [ 5  6  7]
  [ 8  9 10]]]


In [44]:
i = np.array([[1,2,3], [5,6,7]])

In [45]:
print(np.where(i == 7))

(array([1]), array([2]))


In [46]:
r = np.array([10, 12, 9])

In [50]:
s = r.copy()
s[1] = 25
print(r)
print(s)

[10 12  9]
[10 25  9]


In [52]:
t = np.array([13,45,67])
e = t.view()
e[2] = 39
print(e)
print(t)

[13 45 39]
[13 45 39]


In [53]:
b = np.array([3,5,6,7,8,9])

In [54]:
print(b[2:5])

[6 7 8]
